name: Deploy
on: [push, pull_request]

env:
  TEST_TAG: ${{ secrets.DOCKER_USERNAME }}/existdb:experimental

jobs:
  build:
    name: Build and Test Images
    runs-on: ubuntu-latest
    # NOTE (DP): Publish on develop and main, test on PRs against these
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.base_ref ==  'develop' || github.base_ref ==  'main'
    steps:
    
    # SETUP
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64 
          # platforms: all

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make buildkit default
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Install bats and Saxon
        run: sudo apt-get install bats libsaxonb-java

      # ENV Checks
      # - name: Test multi-arch env
      #   run: ./check-qemu-env.sh

      - name: Check local images
        run: docker image ls

      # BUILD
      - name: Modify logging config
        run: saxonb-xslt -s:dump/exist-distribution-5.4.0/etc/log4j2.xml -xsl:log4j2-docker.xslt -o:log4j2.xml

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}  

      # TEST
      - name: Start exist-ci container
        run: |
          docker run -dit -p 8080:8080 --name exist-ci --rm ${{ env.TEST_TAG }}
          sleep 35s

      - name: Run tests
        run: bats --tap test/bats/*.bats

      # PUSH
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/existdb:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/existdb:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/existdb:buildcache,mode=max     
